final dataAppintments = [
  {
    'id': '1',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '2',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '3',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '4',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '5',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '6',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '7',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
  {
    'id': '8',
    'name': 'Dr. Juan Perez',
    'date': '2021-09-01',
    'time': '10:00',
    'status': 'Pendiente',
    'description': 'Consulta de rutina',
  },
];
